version: '3.7'

services:
  config-service:
    container_name: config-service
    image: cheuseanghai/config-server:0.0.1
    ports:
      - 8888:8888
    environment:
      - SPRING_SECURITY_USER_NAME=${USERNAME}
      - SPRING_SECURITY_USER_PASSWORD=${PASSWORD}
