version: '3.7'

services:
  discovery:
    container_name: discovery
    image: cheuseanghai/discovery:0.0.4
    ports:
      - 8761:8761
    environment:
      - SPRING_SECURITY_USER_NAME=${USERNAME}
      - SPRING_SECURITY_USER_PASSWORD=${PASSWORD}
      - EUREKA_INSTANCE_HOSTNAME=localhost
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
