version: '3.7'

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:14.2
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hello
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5433:80
    volumes:
      - pgadmindata:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=cheuseanghai23@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10

volumes:
  postgresdata:
  pgadmindata:
